[package]
edition = "2018"
name = "stardust-xr-server"
version = "0.10.2"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Stardust XR reference display server"
license = "GPLv2"
repository = "https://github.com/StardustXR/stardust-xr-server/"
homepage = "https://stardustxr.org"

[dependencies]
anyhow = "1.0.57"
clap = { version = "4.0.8", features = ["derive"] }
ctrlc = "3.2.2"
dashmap = "5.3.4"
flatbuffers = "22.9.29"
flexbuffers = "2.0.0"
glam = {version = "0.22.0", features = ["mint"]}
lazy_static = "1.4.0"
mint = "0.5.9"
nanoid = "0.4.0"
once_cell = "1.12.0"
parking_lot = "0.12.1"
portable-atomic = {version = "0.3.0", features = ["float", "std"]}
rccell = "0.1.3"
rustc-hash = "1.1.0"
slab = "0.4.6"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.31"
send_wrapper = "0.6.0"
prisma = "0.1.1"
slog = "2.7.0"
slog-stdlog = "4.1.1"
xkbcommon = { version = "0.5.0", default-features = false, optional = true }
stardust-xr = "0.7.1"
directories = "4.0.1"
serde = { version = "1.0.145", features = ["derive"] }

[dependencies.stereokit]
default-features = false
features = ["linux-egl"]
version = "0.5.0"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
default-features = false
features = ["desktop", "renderer_gl", "wayland_frontend"]
version = "*"
optional = true

[features]
default = ["wayland"]
wayland = ["dep:smithay", "dep:xkbcommon"]
